spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/helperbot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    connect-retries: 3

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

services:
  user-vacancy:
    url: http://localhost:8082
  ai-resume:
    url: http://localhost:8081
  news:
    url: http://localhost:8083
