spring.application.name=bot-gateway-service

server.port=8080

spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# application.properties
#logging.level.ru.bot.HelperBot=INFO
#logging.level.org.springframework.web=INFO
#logging.level.org.telegram=INFO
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
