version: '3.8'

services:
#  vpn:
#    image: qmcgaw/gluetun
#    container_name: bot_vpn
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    ports:
#      - "8080:8080"
#    environment:
#      - VPN_SERVICE_PROVIDER=custom
#      - VPN_TYPE=openvpn
#      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
##      - OPENVPN_USER=${OPENVPN_USER}
##      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
#    volumes:
#      - ./vpn/VPNTYPE-PRA3-TCP.conf:/gluetun/custom.conf
#    networks:
#      - app-network
#    restart: unless-stopped

  bot-gateway-service:
    build:
      context: .
      dockerfile: bot-gateway-service/docker/Dockerfile
    image: bot_gateway_service
    container_name: bot_gateway_service
#    network_mode: "service:vpn"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./bot-gateway-service:/app
    depends_on:
#      vpn:
#         condition: service_started
      postgres:
        condition: service_healthy
      ai-resume-service:
        condition: service_started
    networks:
      - app-network

  user-vacancy-service:
    build:
      context: .
      dockerfile: user-vacancy-service/docker/Dockerfile
    image: user_vacancy_service
    container_name: user_vacancy_service
    ports:
      - "8082:8082"
    volumes:
      - ./user-vacancy-service:/app

    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  ai-resume-service:
    build:
      context: .
      dockerfile: ai-resume-service/docker/Dockerfile
    image: ai_resume_service
    container_name: ai_resume_service
    ports:
      - "8081:8081"
    volumes:
      - ./ai-resume-service:/app

    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_started
    networks:
      - app-network

  news-service:
    build:
      context: .
      dockerfile: news-service/docker/Dockerfile
    image: news-service
    container_name: news_service
    ports:
      - "8083:8083"
    volumes:
      - ./news-service:/app
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-ai
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  postgres:
    image: postgres:16
    container_name: postgres_bot
    env_file:
      - .env
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: bot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "raw", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  ollama_data:

networks:
  app-network:
    driver: bridge
