
#telegram:
#  bot:
#    username: ${TELEGRAM_BOT_USERNAME}
#    token: ${TELEGRAM_BOT_TOKEN}

ollama:
  url: http://ollama:11434
  model: ilyagusev/saiga_nemo_12b
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/helperbot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
