spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/helperbot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    connect-retries: 3
    placeholders:
      flyway.ignoreUnknownDatabase: true

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
