spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/helperbot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379

hh:
  access:
    token: ${HH_ACCESS_TOKEN}

services:
  gateway:
    url: http://localhost:8080

vacancy:
  notifications:
    delay-ms: 180000
    initial-delay-ms: 60000
    lookback-minutes: 3
